FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /usr/app

# copy package.json
COPY package.json ./

# copy yarn.lock
COPY yarn.lock ./

# install project dependencies
RUN yarn install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . ./